server:
  port: 89

spring:
  #配置数据源
  datasource:
    #配置数据源类型
    type: com.alibaba.druid.pool.DruidDataSource
    #配置连接数据库的信息
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:192.168.137.1:3306/sql_security?characterEncoding=utf8&useSSL=false&serverTimezone=CTT&rewriteBatchedStatements=true
    username: root
    password: root123


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/**/*.xml